name: fiberhome-password

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fiberhome-frontend
    expose:
      - "8000"
    ports:
      - "3000:8000"
    restart: always
